train:
  - _target_: src.metrics.jepa.JEPAMetric
    metric_type: cosine
    name: "TRAIN_CosineSimilarity"
  - _target_: src.metrics.jepa.JEPAMetric
    metric_type: mse
    name: "TRAIN_MSE"

inference:
  - _target_: src.metrics.jepa.JEPAMetric
    metric_type: cosine
    name: "CosineSimilarity"
  - _target_: src.metrics.jepa.JEPAMetric
    metric_type: mse
    name: "MSE"
  - _target_: src.metrics.linear_probe.LinearProbeMetric
    embed_dim: 16
    num_classes: 100
    probe_epochs: 2
    name: "LinearProbe"