_target_: src.model.models.VisionTransformer
img_size: [32]
patch_size: 4
in_chans: 3
embed_dim: 16
predictor_embed_dim: 8
depth: 2
predictor_depth: 2
num_heads: 2
mlp_ratio: 2.0
qkv_bias: True
qk_scale: null
drop_rate: 0.0
attn_drop_rate: 0.0
drop_path_rate: 0.0
#norm_layer: nn.LayerNorm
init_std: 0.02
