_target_: src.model.models.IJEPAWrapper
momentum: 0.996

context_encoder:
  _target_: src.model.models.VisionTransformer
  img_size: [32]
  patch_size: 4
  in_chans: 3
  embed_dim: 288
  predictor_embed_dim: 192
  depth: 10
  predictor_depth: 8
  num_heads: 6
  mlp_ratio: 4.0
  qkv_bias: True
  qk_scale: null
  drop_rate: 0.0
  attn_drop_rate: 0.0
  drop_path_rate: 0.0
  init_std: 0.02

predictor:
  _target_: src.model.universal_transformer.UniversalTransformerPredictor
  num_patches: 64
  embed_dim: 288
  predictor_embed_dim: 192
  time_emb: True
  depth: 8
  num_heads: 6
  mlp_ratio: 4.0
  qkv_bias: True
  qk_scale: null
  drop_rate: 0.0
  attn_drop_rate: 0.0
  drop_path_rate: 0.0
  init_std: 0.02
