defaults:
  - model: jepa_3
  - writer: wandb
  - metrics: metrics_2
  - datasets: cifar10
  - dataloader: dataloader_2
  - loss_function: jepa
  - transforms: cifar_transform
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-3
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  total_steps: null # само посчитает @!%*& 
  pct_start: 0.20
  max_lr: 1e-4
  div_factor: 500.0
  final_div_factor: 0.1 
visualization:
  _target_: src.metrics.AttentionVisualizer
  enabled: True
  split: test
  num_images: 10
  seed: 42
  log_every_n_epochs: 5
  encoder_layers: [0, 1, 2, 3, 4, 5, 6, 7]
  predictor_layers: null
  alpha: 0.55
  image_name_prefix: attn
trainer:
  log_step: null
  n_epochs: 100
  n_epoch_probe: 5
  epoch_len: null
  device_tensors: ["image", "fine_label"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: "auto" # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
