_target_: torch.utils.data.DataLoader
batch_size: 256
num_workers: 2
pin_memory: True
collate_fn:
  _target_: src.masks.MaskCollatorMultiBlock
  input_size: 32
  patch_size: 4
  enc_mask_scale: [0.4, 0.6]
  pred_mask_scale: [0.15, 0.2]
  aspect_ratio: [0.75, 1.5]
  nenc: 1
  npred: 1
  min_keep: 3
  allow_overlap: False
