train:
  image: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.RandomResizedCrop
        size: [32, 32]
        scale: [0.4, 1.0]
        ratio: [0.75, 1.33]
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
        p: 0.5
      - _target_: torchvision.transforms.v2.ColorJitter
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1
        p: 0.8
      - _target_: torchvision.transforms.v2.RandomGrayscale
        p: 0.2
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]

inference:
  image: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
